# Generated by Django 5.0.2 on 2024-04-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uwu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=15)),
                ('l_name', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(max_length=15)),
            ],
        ),
    ]
